### ISSUE TITLE
Приведение Int к Float перед отправкой в API CloudPayments

### ISSUE THREAD

**Issue by karpyzin** [cloudpayments/CloudPayments-SDK-Android#16]
**Проблема**:
ViewModel экрана библиотеки конвертирует все Int поля в Float перед тем, как отправить на бекенд

**Детально**:
При запуске процесса оплаты я передаю объект `PaymentConfiguration`, в который передаю `PaymentData`. У PaymentData есть опциональное поле `jsonData`, в которое можно передавать `String?`.  При инициализации платежа я помещаю в `jsonData` строку, пример `{"interval":"Month","period":1} `, это поле идет до PaymentProcessViewModel, где преобразует строку обратно в JsonObject через Gson. После чего все числа типа Int преобразуются в Float и в таком виде отправляются на бекенд CloudPayments, пример `{"interval":"Month","period":1.0} `

Подробное описание проблемы здесь: https://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats

<img width="1082" alt="image" src="https://github.com/cloudpayments/CloudPayments-SDK-Android/assets/18004167/1c9d40e2-8559-4e0d-8a85-9640f1e6c0cf">

**Comment by a-ignatov-cp** [comment]
Исправлено в версии 1.3.3
