### ISSUE TITLE
AppCompatActivity в качестве обязательного параметра

### ISSUE THREAD

**Issue by NikitaVasin** [cloudpayments/CloudPayments-SDK-Android#4]
Привет!
Я пытаюсь встроить SDK в Flutter приложение.
Возможно ли сделать чтобы в метод launcher можно было передавать FragmentActivity?
Сейчас, в метод создания лаунчера необходимо передавать AppCompatActivity, но дело в том что активити в котором запускается флаттер наследует FragmentActivity, а в свою очередь AppCompаtActivity так же наследуется от FragmentActivity. Основное отличие AppCompаtActivity от FragmentActivity в том что в нем переопределена тема (что на мой взгляд не критично).
К сожалению во флатере нет активити которые наследуются от AppCompatActivity

**Comment by a-ignatov-cp** [comment]
Please use version 1.1.9
