### ISSUE TITLE
Не могу подтянуть зависимость, mac m1 pro

### ISSUE THREAD

**Issue by tergeoo** [cloudpayments/CloudPayments-SDK-Android#8]
Подскажите может кто сталкивался, или как это фиксить

**Comment by tergeoo** [comment]
![Uploading Снимок экрана 2022-11-19 в 17.26.41.png…]()

**Comment by tergeoo** [comment]
![Uploading Снимок экрана 2022-11-19 в 17.27.22.png

**Comment by tergeoo** [comment]
![Снимок экрана 2022-11-19 в 17 30 34](https://user-images.githubusercontent.com/50424312/202855868-fd7a24e5-6411-4da4-a163-80bc3cb6b40a.png)

**Comment by glebosotov** [comment]
Добавьте дополнительный источник в `build.gradle` уровня проекта. Это есть в README проекта.

```gradle
allprojects {
    repositories {
        google()
        mavenCentral()
        // This one below
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by a-ignatov-cp** [comment]
Либо это Вам необходимо сделать в файле settings.gradle:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```
